#!/usr/bin/env bash

set -eo nounset -o pipefail

clusterName="$1"
awsProfile="${2:-default}"

[ -z "$clusterName" ] && echo "Must provide EKS cluster name to first argument" && exit 123

ips="$(aws ec2  describe-network-interfaces --filters Name=description,Values="Amazon EKS $clusterName" | grep "PrivateIpAddress\"" | cut -d ":" -f 2 |  sed 's/[*",]//g' | sed 's/^\s*//'| uniq)"
endpoint="$(aws eks describe-cluster --name "$clusterName" --profile "$awsProfile" | grep endpoint\" | cut -d ":" -f 3 | sed 's/[\/,"]//g')"
IFS=$'\n' 
           
echo "Pulling EKS kubeconfig to local"

echo "Creating backup of /etc/hosts"
sudo cp /etc/hosts /etc/hosts_backup
sudo sh -c "cat /etc/hosts  | grep -v $endpoint > /etc/hosts_new"

for item in $ips
do
    sudo sh -c "echo $item  $endpoint >> /etc/hosts_new"
done

echo "Updating cluster IP to /etc/hosts"
sudo sh -c "cat /etc/hosts_new > /etc/hosts"

